class ChargingStation:
    def __init__(self, data):
        self.betreiber = data.get("Betreiber")
        self.name = data.get("Name")
        self.strasse = data.get("Straße")
        self.hausnummer = data.get("Hausnummer")
        self.adresszusatz = data.get("Adresszusatz")
        self.plz = data.get("PLZ")
        self.ort = data.get("Ort")
        self.kreis_kreisfreie_stadt = data.get("Kreis/kreisfreie Stadt")
        self.bundesland = data.get("Bundesland")
        self.latitude = data.get("Latitude")
        self.longitude = data.get("Longitude")
        self.inbetriebnahmedatum = data.get("Inbetriebnahmedatum")
        self.nennleistung_ladeeinrichtung_kw = data.get("Nennleistung Ladeeinrichtung [kW]")
        self.art_der_ladeeinrichtung = data.get("Art der Ladeeinrichtung")
        self.anzahl_ladepunkte = data.get("Anzahl Ladepunkte")
        self.steckertypen1 = data.get("Steckertypen1")
        self.p1_kw = data.get("P1 [kW]")
        self.public_key1 = data.get("Public Key1")
        self.steckertypen2 = data.get("Steckertypen2")
        self.p2_kw = data.get("P2 [kW]")
        self.public_key2 = data.get("Public Key2")
        self.steckertypen3 = data.get("Steckertypen3")
        self.p3_kw = data.get("P3 [kW]")
        self.public_key3 = data.get("Public Key3")
        self.steckertypen4 = data.get("Steckertypen4")
        self.p4_kw = data.get("P4 [kW]")
        self.public_key4 = data.get("Public Key4")
        self.steckertypen5 = data.get("Steckertypen5")
        self.p5_kw = data.get("P5 [kW]")
        self.public_key5 = data.get("Public Key5")
        self.steckertypen6 = data.get("Steckertypen6")
        self.p6_kw = data.get("P6 [kW]")
        self.public_key6 = data.get("Public Key6")
        self.address = data.get("Address")
        self.id = data.get("id")

    def __str__(self):
        return f"ChargingStation(id={self.id}, name={self.name}, address={self.address})"